const fr = {
  'titre.appuie': 'Appuie sur une touche',
  'titre.disclaimer': 'Jeu de fan non commercial — non affilié à EXOK Games',
  'titre.jouer': 'Jouer',
  'titre.options': 'Options',
  'titre.credits': 'Crédits',
  'titre.quitter': 'Quitter',

  'sauvegardes.titre': 'Les ascensions',
  'sauvegardes.slotVide': 'Vide — commencer une ascension',
  'sauvegardes.nomQuestion': 'Ton nom de grimpeur ?',
  'sauvegardes.confirmerSuppression': 'Tout effacer ? Entrée pour confirmer',
  'sauvegardes.aide': '↑↓ choisir · Entrée ouvrir · Suppr effacer · Échap retour',

  'options.titre': 'Options',
  'options.langue': 'Langue',
  'options.volume': 'Volume',
  'options.taillePolice': 'Taille du texte',
  'options.taille.petite': 'Petite',
  'options.taille.normale': 'Normale',
  'options.taille.grande': 'Grande',
  'options.aide': 'Échap retour',

  'credits.titre': 'Crédits',
  'credits.texte': 'PyQuest — un jeu de fan, hommage à Celeste.',
  'credits.celeste':
    'Celeste, son univers et ses assets sont la propriété de Maddy Makes Games, Inc. (EXOK Games).',
  'credits.musique': 'Musique originale de Celeste : Lena Raine (éditée par Materia Collective).',
  'credits.disclaimer':
    'Projet strictement non commercial, ni développé, ni approuvé, ni affilié à EXOK Games. Tout asset sera retiré sur simple demande d’un ayant droit.',
  'credits.aide': 'Échap retour',

  'carte.titre': 'Le mont PyQuest',
  'carte.salles': 'salles',
  'carte.chutes': 'chutes',
  'carte.aVenir': 'à venir',
  'carte.verrouille': 'verrouillé',
  'carte.ascension': 'ascension',
  'carte.aide': '↑↓ choisir · Entrée gravir · Échap retour',

  'salle.lancer': '▶ Lancer',
  'salle.consoleInvite': 'Lance ton code pour voir ce qu’il affiche (Ctrl+Entrée)',
  'salle.preparation': 'Préparation de Python…',
  'salle.execution': 'Exécution…',
  'salle.validee': 'Salle validée !',
  'salle.suivante': 'Salle suivante : Entrée',
  'salle.finChapitre': 'Chapitre terminé ! Retour à la carte : Entrée',
  'salle.chute': 'Chute !',
  'salle.test': 'Test',
  'salle.entrees': 'entrées fournies',
  'salle.attendu': 'Attendu',
  'salle.obtenu': 'Obtenu',
  'salle.erreurLigne': 'ligne',
  'salle.timeout': 'Ton programme tournait encore après 5 secondes — boucle infinie ?',
  'salle.erreurAttendue': 'Ton programme s’est déroulé sans accroc… il fallait le faire planter !',
  'salle.erreurObtenue': 'Belle erreur !',
  'salle.indice': 'Indice',
  'salle.confirmerSolution': 'Tu y es presque… Encore Ctrl+H et je te montre la solution.',
  'salle.aide': 'Ctrl+Entrée lancer · Ctrl+H indice · Échap carte',
};

export type CleTexte = keyof typeof fr;

const en: Record<CleTexte, string> = {
  'titre.appuie': 'Press any key',
  'titre.disclaimer': 'Non-commercial fan game — not affiliated with EXOK Games',
  'titre.jouer': 'Play',
  'titre.options': 'Options',
  'titre.credits': 'Credits',
  'titre.quitter': 'Quit',

  'sauvegardes.titre': 'Ascents',
  'sauvegardes.slotVide': 'Empty — start an ascent',
  'sauvegardes.nomQuestion': 'Your climber name?',
  'sauvegardes.confirmerSuppression': 'Erase everything? Enter to confirm',
  'sauvegardes.aide': '↑↓ select · Enter open · Del erase · Esc back',

  'options.titre': 'Options',
  'options.langue': 'Language',
  'options.volume': 'Volume',
  'options.taillePolice': 'Text size',
  'options.taille.petite': 'Small',
  'options.taille.normale': 'Normal',
  'options.taille.grande': 'Large',
  'options.aide': 'Esc back',

  'credits.titre': 'Credits',
  'credits.texte': 'PyQuest — a fan game, tribute to Celeste.',
  'credits.celeste':
    'Celeste, its universe and its assets are the property of Maddy Makes Games, Inc. (EXOK Games).',
  'credits.musique': 'Original Celeste music: Lena Raine (published by Materia Collective).',
  'credits.disclaimer':
    'Strictly non-commercial project, neither developed, approved, nor affiliated with EXOK Games. Any asset will be removed upon request from a rights holder.',
  'credits.aide': 'Esc back',

  'carte.titre': 'Mount PyQuest',
  'carte.salles': 'rooms',
  'carte.chutes': 'falls',
  'carte.aVenir': 'coming soon',
  'carte.verrouille': 'locked',
  'carte.ascension': 'ascent',
  'carte.aide': '↑↓ select · Enter climb · Esc back',

  'salle.lancer': '▶ Run',
  'salle.consoleInvite': 'Run your code to see what it prints (Ctrl+Enter)',
  'salle.preparation': 'Warming up Python…',
  'salle.execution': 'Running…',
  'salle.validee': 'Room cleared!',
  'salle.suivante': 'Next room: Enter',
  'salle.finChapitre': 'Chapter complete! Back to the map: Enter',
  'salle.chute': 'Fall!',
  'salle.test': 'Test',
  'salle.entrees': 'inputs provided',
  'salle.attendu': 'Expected',
  'salle.obtenu': 'Got',
  'salle.erreurLigne': 'line',
  'salle.timeout': 'Your program was still running after 5 seconds — infinite loop?',
  'salle.erreurAttendue': 'Your program ran without a hitch… you were supposed to crash it!',
  'salle.erreurObtenue': 'What a beautiful error!',
  'salle.indice': 'Hint',
  'salle.confirmerSolution': 'So close… Ctrl+H once more and I’ll show you the solution.',
  'salle.aide': 'Ctrl+Enter run · Ctrl+H hint · Esc map',
};

export const textes = { fr, en };
